#!/usr/bin/env python3
"""Collect actual locked dependency notices; no network license-text substitutions."""
import argparse
import hashlib
import json
import re
import subprocess
from html.parser import HTMLParser
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
TARGETS = ("x86_64-pc-windows-msvc", "aarch64-pc-windows-msvc", "aarch64-apple-darwin")
NOTICE_NAME = re.compile(r"^(?:licen[cs]e|copying|notice|copyright)(?:[._-]|$)", re.I)
SUPPLEMENTAL = {
    ("asn1-rs-impl", "0.2.0"): {
        "LICENSE-MIT": "a5c61b93b6ee1d104af9920cf020ff3c7efe818e31fe562c72261847a728f513",
        "LICENSE-APACHE": "a60eea817514531668d7e00765731449fe14d059d3249e0bc93b36de45f759f2",
    }
}


def command(*args):
    return subprocess.check_output(args, cwd=ROOT, text=True, encoding="utf-8")


class LibraryNotice(HTMLParser):
    def __init__(self):
        super().__init__()
        self.text = []
        self.licenses = set()
        self.ignored = 0

    def handle_starttag(self, tag, attrs):
        if tag in ("style", "script"):
            self.ignored += 1
        if tag in ("p", "div", "br", "h1", "h2", "h3", "li", "pre"):
            self.text.append("\n")
        for name, value in attrs:
            if name == "href" and value and value.startswith("licenses/"):
                self.licenses.add(value)

    def handle_endtag(self, tag):
        if tag in ("style", "script"):
            self.ignored -= 1
        if tag in ("p", "div", "h1", "h2", "h3", "li", "pre"):
            self.text.append("\n")

    def handle_data(self, data):
        if not self.ignored:
            self.text.append(data)


def collect():
    packages = {}
    for target in TARGETS:
        metadata = json.loads(command("cargo", "metadata", "--locked", "--format-version", "1", "--filter-platform", target))
        selected = {node["id"] for node in metadata["resolve"]["nodes"]}
        for package in metadata["packages"]:
            if package["id"] in selected and package.get("source"):
                packages[package["id"]] = package
    texts = {}

    def record(label, text):
        text = text.replace("\r\n", "\n").strip() + "\n"
        if not text.strip():
            raise ValueError(f"Empty license: {label}")
        key = hashlib.sha256(text.encode()).hexdigest()
        texts.setdefault(key, {"labels": [], "text": text})["labels"].append(label)
        return key

    lines = [
        "Codlet third-party Rust dependency notices",
        "Generated by scripts/collect-rust-licenses.py from locked crate contents.",
        "Includes resolved build/runtime dependencies for: " + ", ".join(TARGETS),
        "Some dependencies are platform-specific. Each retains its own license.",
        "Identical notice texts are printed once and referenced by SHA-256.",
        "Cargo.lock SHA-256: " + hashlib.sha256((ROOT / "Cargo.lock").read_bytes().replace(b"\r\n", b"\n")).hexdigest(),
        "",
    ]
    for package in sorted(packages.values(), key=lambda p: (p["name"], p["version"])):
        directory = Path(package["manifest_path"]).parent
        files = {path for path in directory.rglob("*") if path.is_file() and NOTICE_NAME.match(path.name)}
        if package.get("license_file"):
            files.add(directory / package["license_file"])
        supplemental = SUPPLEMENTAL.get((package["name"], package["version"]))
        if not files and supplemental:
            # This crate omitted workspace license files from its archive.
            # Reviewed texts come from its exact published VCS revision.
            directory = ROOT / "scripts/licenses" / f"{package['name']}-{package['version']}"
            for name, expected in supplemental.items():
                file = directory / name
                if hashlib.sha256(file.read_bytes().replace(b"\r\n", b"\n")).hexdigest() != expected:
                    raise ValueError(f"Supplemental license digest mismatch: {name}")
                files.add(file)
        if not files:
            raise ValueError(f"No license/notice text shipped by {package['name']} {package['version']}")
        label = f"{package['name']} {package['version']}"
        lines.extend([label, "Declared license: " + (package.get("license") or "see supplied license file"), "Source: " + package["source"]])
        for file in sorted(files):
            relative = file.relative_to(directory).as_posix()
            key = record(f"{label}/{relative}", file.read_text(encoding="utf-8-sig"))
            lines.append(f"  {relative}: {key}")
        lines.append("")
    rust_version = command("rustc", "--version").strip()
    rust_docs = Path(command("rustc", "--print", "sysroot").strip()) / "share/doc/rust"
    library = LibraryNotice()
    library.feed((rust_docs / "COPYRIGHT-library.html").read_text(encoding="utf-8"))
    key = record(rust_version + "/COPYRIGHT-library.html (text)", re.sub(r"\n[ \t]*\n(?:[ \t]*\n)+", "\n\n", "".join(library.text)))
    lines.extend([rust_version + " standard library", "  COPYRIGHT-library.html: " + key])
    for relative in sorted(library.licenses):
        file = rust_docs / relative
        if not file.resolve().is_relative_to(rust_docs.resolve()):
            raise ValueError("Unexpected Rust notice path")
        key = record(rust_version + "/" + relative, file.read_text(encoding="utf-8-sig"))
        lines.append(f"  {relative}: {key}")
    for key in sorted(texts):
        item = texts[key]
        lines.extend(["", "=" * 72, "Notice SHA-256: " + key, "Used by:", *["  " + label for label in sorted(item["labels"])], "", item["text"].rstrip()])
    return "\n".join(lines) + "\n", len(packages), len(texts)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail when committed notices differ")
    args = parser.parse_args()
    text, packages, notices = collect()
    output = ROOT / "docs/THIRD_PARTY_RUST_LICENSES.txt"
    if args.check:
        if not output.is_file() or output.read_text(encoding="utf-8") != text:
            raise SystemExit("Rust notices are stale; run scripts/collect-rust-licenses.py")
    else:
        output.write_text(text, encoding="utf-8", newline="\n")
    print(f"Rust attribution: {packages} locked dependencies, {notices} distinct notices")


if __name__ == "__main__":
    main()
