[CmdletBinding()]
param(
    [Parameter(Mandatory = $true)][string]$Destination,
    [ValidateSet('win-x64', 'win-arm64')][string]$Platform,
    [string]$ArchivePath
)
$ErrorActionPreference = 'Stop'
if (-not $Platform) {
    $architecture = [System.Runtime.InteropServices.RuntimeInformation]::OSArchitecture.ToString()
    $Platform = switch ($architecture) {
        'X64' { 'win-x64' }
        'Arm64' { 'win-arm64' }
        default { throw "Unsupported Windows architecture: $architecture" }
    }
}
$lockPath = Join-Path $PSScriptRoot '../runtime/node-runtime.json'
$lock = [System.IO.File]::ReadAllText($lockPath) | ConvertFrom-Json
$platformSpec = $lock.platforms.$Platform
$root = [System.IO.Path]::GetFullPath($Destination)
$runtimeDirectory = Join-Path $root ("runtime/node-v{0}-{1}" -f $lock.version, $Platform)
$nodePath = Join-Path $runtimeDirectory 'node.exe'
$licensePath = Join-Path $runtimeDirectory 'LICENSE'
if ((Test-Path -LiteralPath $nodePath) -and (Test-Path -LiteralPath $licensePath)) {
    if (((Get-FileHash -LiteralPath $nodePath -Algorithm SHA256).Hash -ieq $platformSpec.executableSha256) -and
        ((Get-FileHash -LiteralPath $licensePath -Algorithm SHA256).Hash -ieq $platformSpec.licenseSha256)) {
        Write-Output "JS runtime ready: $nodePath"
        return
    }
    throw "The managed runtime has a different hash: $nodePath. Repair this version directory before staging again."
}
New-Item -ItemType Directory -Path $runtimeDirectory -Force | Out-Null
$temporaryArchive = $null
$temporaryNode = Join-Path $runtimeDirectory ('.node-' + [Guid]::NewGuid().ToString('N') + '.tmp')
$temporaryLicense = Join-Path $runtimeDirectory ('.license-' + [Guid]::NewGuid().ToString('N') + '.tmp')
try {
    if (-not $ArchivePath) {
        $temporaryArchive = Join-Path $runtimeDirectory ('.download-' + [Guid]::NewGuid().ToString('N') + '.zip')
        $ArchivePath = $temporaryArchive
        $url = $lock.baseUrl + '/' + $platformSpec.archive
        # curl is bundled with supported Windows versions. No shell fragments,
        # install hooks, package manager, PATH edits or plugin execution occur.
        & curl.exe --fail --silent --show-error --location --connect-timeout 15 --max-time 180 --output $ArchivePath $url
        if ($LASTEXITCODE -ne 0) { throw "Node download failed with curl exit $LASTEXITCODE" }
    }
    $ArchivePath = [System.IO.Path]::GetFullPath($ArchivePath)
    if ((Get-FileHash -LiteralPath $ArchivePath -Algorithm SHA256).Hash -ine $platformSpec.archiveSha256) {
        throw 'Node archive hash differs from the checked-in runtime pin.'
    }
    Add-Type -AssemblyName System.IO.Compression.FileSystem
    $archive = [System.IO.Compression.ZipFile]::OpenRead($ArchivePath)
    try {
        $prefix = 'node-v' + $lock.version + '-' + $Platform + '/'
        foreach ($item in @(@('node.exe', $temporaryNode), @('LICENSE', $temporaryLicense))) {
            $entry = $archive.GetEntry($prefix + $item[0])
            if (-not $entry) { throw ('Missing official archive member: ' + $item[0]) }
            $inputStream = $entry.Open()
            $outputStream = [System.IO.File]::Open($item[1], [System.IO.FileMode]::CreateNew)
            try { $inputStream.CopyTo($outputStream) } finally { $outputStream.Dispose(); $inputStream.Dispose() }
        }
    } finally { $archive.Dispose() }
    if ((Get-FileHash -LiteralPath $temporaryNode -Algorithm SHA256).Hash -ine $platformSpec.executableSha256) {
        throw 'Node executable hash differs from the checked-in runtime pin.'
    }
    if ((Get-FileHash -LiteralPath $temporaryLicense -Algorithm SHA256).Hash -ine $platformSpec.licenseSha256) {
        throw 'Node license hash differs from the checked-in runtime pin.'
    }
    Move-Item -LiteralPath $temporaryNode -Destination $nodePath -Force
    Move-Item -LiteralPath $temporaryLicense -Destination $licensePath -Force
    Write-Output "JS runtime staged: $nodePath"
} finally {
    # Delete only the three exact temporary files generated by this invocation.
    foreach ($temporary in @($temporaryArchive, $temporaryNode, $temporaryLicense)) {
        if ($temporary -and (Test-Path -LiteralPath $temporary -PathType Leaf)) {
            Remove-Item -LiteralPath $temporary -Force
        }
    }
}
