pub mod control_pipe;
mod control_scope;
pub mod environment;
pub mod fake_child;
pub mod launch_mutex;
pub(crate) mod local_ipc;
pub mod packages;
pub mod pipes;
pub(crate) mod plugin_process;
pub mod process;
pub mod status_pipe;
