// Generated by frontend/build.mjs; edit frontend/src. OpenAI Apps SDK UI 0.2.2, React 19.2.0.
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/examples/ui-controls.jsx
var ui_controls_exports = {};
__export(ui_controls_exports, {
  activate: () => activate,
  deactivate: () => deactivate
});
module.exports = __toCommonJS(ui_controls_exports);
var React;
var h;
var C;
var ui;
function Example() {
  const [value, setValue] = React.useState(0), [enabled, setEnabled] = React.useState(true), [busy, setBusy] = React.useState(false), [confirm, setConfirm] = React.useState(false);
  ui.useEscCloseStack(confirm, () => setConfirm(false));
  React.useEffect(() => {
    if (!busy) return;
    const timer = setTimeout(() => {
      setValue((v) => v + 1);
      setBusy(false);
    }, 500);
    return () => clearTimeout(timer);
  }, [busy]);
  return /* @__PURE__ */ h("section", { "aria-label": "Official UI controls", style: { padding: 32, maxWidth: 760, margin: "0 auto", display: "flex", flexDirection: "column", gap: 16 } }, /* @__PURE__ */ h("h1", null, "Official UI controls"), /* @__PURE__ */ h("p", null, "Counter: ", value), /* @__PURE__ */ h(C.Switch, { checked: enabled, onCheckedChange: setEnabled, label: "Enabled" }), /* @__PURE__ */ h("div", { style: { display: "flex", flexWrap: "wrap", gap: 8 } }, /* @__PURE__ */ h(C.Button, { color: "primary", size: "md", disabled: !enabled, onClick: () => setValue((v) => v + 1) }, "Increment"), /* @__PURE__ */ h(C.Button, { color: "secondary", variant: "soft", size: "md", loading: busy, disabled: busy, onClick: () => setBusy(true) }, "Run"), /* @__PURE__ */ h(C.Button, { color: "secondary", variant: "ghost", size: "md", onClick: () => setConfirm(true) }, "Reset\u2026")), confirm && /* @__PURE__ */ h("div", { role: "group", "aria-label": "Reset counter?" }, /* @__PURE__ */ h("p", null, "Reset counter?"), /* @__PURE__ */ h(C.Button, { color: "secondary", variant: "ghost", size: "sm", onClick: () => setConfirm(false) }, "Cancel"), /* @__PURE__ */ h(C.Button, { color: "danger", size: "sm", onClick: () => {
    setValue(0);
    setConfirm(false);
  } }, "Reset")));
}
function deactivate() {
  ui?.dispose();
  ui = null;
}
async function activate(context) {
  deactivate();
  context.onDeactivate(deactivate);
  ui = context.ui.create();
  ({ React, components: C } = ui);
  h = React.createElement;
  await ui.page({ label: "UI controls", icon: "CodeSquareSlash", render: () => /* @__PURE__ */ h(Example, null) });
}
